### ISSUE TITLE
changing the lightPositionOffset sliders has no effect

### ISSUE THREAD

**Issue by yellowtailfan** [bandicoot-imaging-sciences/bivot#28]
`state.lightPositionOffset` keeps the initial value (from the JSON files or the default) instead of picking up changes made in the DAT GUI sliders.

**Comment by yellowtailfan** [comment]
Setting `state.lightPositionOffset` in `bivot-renders.json` also has no effect. Only the values in `bivot-config.json` are used.

**Comment by volrak** [comment]
Vector objects in the state were being mishandled.  Bivot is now:
* Maintaining a vector object in the state which is both written to according to config data, and also referenced by the GUI controls (rather than clobbering the vector object known to the GUI when loading config data)
* Cloning vector objects rather than assigning (by reference) when copying values between initialState and State to ensure these remain different objects (otherwise vector objects in initialState get clobbered whenever those objects in State change)
