### ISSUE TITLE
reset lighting if device tilts away from initial position for a while

### ISSUE THREAD

**Issue by yellowtailfan** [bandicoot-imaging-sciences/bivot#8]
If a phone or tablet user tilts the device a long way away from the initial orientation, the render goes dark. They might not realise they need to go back to the starting angle.

One possible solution would be to have a long timeout (say 5 s) after which if the orientation is more than a certain angle away from the start point, and the RMS of the orientation over the last 5 s is below a threshold, then reset the lighting position to suit the new orientation.

The light could quickly animate from the old position to the new position, to avoid the light suddenly popping into the new spot.

Another approach would be to just have a sliding window (say 5 s) and continuously move the light to the average orientation over that window.

We might also want to move the "overhead" camera view to the same orientation as the light (again with a short transition to smooth the effect).

**Comment by volrak** [comment]
If there are examples of this problem happening to a user, it would be good to record them and try to learn what made the user get lost and why they couldn't recover.

We should avoid solutions which frustrate other users, e.g. those who want to take some time studying the reflection at a non-centered point on the material.  

Depending exactly on where the core of the problem lies, one solution could be to reset the relative tilt upon the device waking up or upon switching apps/tabs back into the browser page containing the render.  Another solution could be to allow the user to reset the view somehow, e.g. by tapping on the render.  A third solution could be to put additional limits on the amount of possible tilt away from the centre.

**Comment by yellowtailfan** [comment]
Resolved in c8a189e121a73820a8ceae1f67988cc00f917e4b.
